sudo: required
services:
  - docker

env:
  global:
    - IMAGE_NAME=${DOCKER_USERNAME}/graalvm

before_script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - VERSION="$(git describe --abbrev=0 --tags --exact-match)"

script:
  - echo Building version ${VERSION}
  - docker build --pull --cache-from "${IMAGE_NAME}" --build-arg "GRAALVM_VERSION=${VERSION}" --tag "${IMAGE_NAME}:${VERSION}" .

after_script:
  - docker images
  - docker run --rm -it "${IMAGE_NAME}:${VERSION}"
  - docker push "${IMAGE_NAME}:${VERSION}"